name: 'Docker build'
description: 'Build and push a docker image to a repository'
inputs:
  image_url:
    description: 'Docker image URL, for example "aws_account_id.dkr.ecr.region.amazonaws.com/my-web-app"'
    required: true
  tags:
    description: 'Comma separated extra tags to push for this image'
    required: false
    default: 'latest'
  login_cmd:
    description: 'The login command for the Docker registry'
    required: true
outputs:
  # github actions doenst support dynamic outputs, hence this duplication
  image0:
    description: "Image pushed"
    value: ${{ steps.build.outputs.image0 }}
  image1:
    description: "Image pushed"
    value: ${{ steps.build.outputs.image0 }}
runs:
  using: "composite"
  steps: 
    - id: build
      run: ${{ github.action_path }}/build-and-push.sh "${{ inputs.image_url }}" "${{ inputs.tags }}" "${{ inputs.login_cmd }}"
      shell: bash
