name: 'Docker build'
description: 'Build and push a docker image to a repository'
inputs:
  image_url:
    description: 'Docker image URL, for example "aws_account_id.dkr.ecr.region.amazonaws.com/my-web-app"'
    required: true
    # default: 'World'
outputs:
  random-number: 
    description: "Random number"
    value: ${{ steps.random-number-generator.outputs.random-id }}
runs:
  using: "composite"
  steps: 
    - run: ${{ github.action_path }}/build-and-push.sh
      shell: bash
