name: test

on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: foo
        uses: mhristof/github-action-test@master
        with:
          image_url: aws_account_id.dkr.ecr.region.amazonaws.com/my-web-app
      

